[package]
name = "rustbouncer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
bytes = "1.11.0"
anyhow = "1.0"